const anime = [
  "Megalo Box 2",
  "patlabor early days",
  "patlabor 1",
  "patlabor 2",
  "dr stone",
  "Infinity train",
  "sangatsu no lion",
  "haibane renmei",
  "kiki's delivery service",
  "alien 9",
  "genshiken",
  "gekkan shoujo nozaki-kun",
  "mushishi",
  "dorohedoro",
  "welcome to NHK",
  "turn a gundam",
  "gundam war in a pocket",
  "yuru camp △",
  "chuunibyou gekihatsu boy",
  "directed by robert b weide",
  "michiko to hatchin",
  "hypnosis mic",
  "udon no kuni no kiniro kemari",
  "tsuki ga kirei",
  "Sora yorimo toi basho",
  "hoshirai no sora",
  "the americans series",
  "barry series",
  "chernovil",
  "so wa no wo to",
];
