const books = [
  "Desobediencia Civil - Henry David Thoreau",
  "El Mundo de Sofia",
  "Ten acts of magic - Los Horcones",
  "El Aleph - jorge luis borges",
  "Otras inquisiciones - jorge luis borges",
  "Las peras del olmo - octavio paz",
  "Fragmentos de un discurso amoroso - roland barthes",
  "Los monstruos y los críticos - jrr tolkien",
  "Realismo Capitalista ¿No hay alternativa? - Mark Fisher",
  "David graeber - En deuda",
  "Michel Onfray - Decadencia - Vida y Muerte de Occidente",
  "Sapiens",
  "El Retrato de Dorian Gray - Oscar Wilde",
  "Perfect vacuum (jaja, cum)",
  "el pensamiento moderno - Luis Villoro",
  "Superinteligencia - Nick Bostrom",
  "El aroma del tiempo - Byung-Chul Han",
  "La sociedad del cansancio - Byung-Chul Han",
  "La agonía del eros - Byung-Chul Han",
  "Hiperculuralidad - Byung-Chul Han",
  "Freixa I Baque - Que es la Conducta",
  "Homo Deus",
  "Grisela Leal - El Club de los Abandonados",
  "Milan Kundera - La Insoportable Levedad del ser",
  "José Trigo - Fernando del Paso",
  "Juan Samaja - Epistemología y Metodología",
  "Jose Cesar Lenin - Epistemología y Metodología",
  "Neal Stephenson - Snow Crash",
  "William Gibson - Neuromente",
  "Douglas Adams - Guía del Autoestopista Galáctico",
  "Greg Egan - Ciudad Permutación",
  "Liu Cixin - El Problema de los Tres Cuerpos",
  "Philip K. Dick - ¿Sueñan los Androides con Ovejas Eléctricas?",
  "Robert F. Young - The Dandelion Girl",
  "Haruki Murakami - Crónica del pajaro que da cuerda al mundo",
  "Robert Jordan - La Rueda del Tiempo 01 - El Ojo del Mundo",
  "Camus - El Mito de Sisifo",
  "Camus - La Peste",
  "Dialogos de Platón 01",
  "El mundo es Matemático 01",
  "Tratado de la Tolerancia - Voltaire",
  "gilgo - traducción de jorge ilva castillo",
  "diario de las estrellas - stainslaw lem",
  "fabulas de robots - stainslaw lem",
  "magnitud imaginaria - stainslaw lem",
  "golem XIV - stainslaw lem",
  "heterogenia linguistico",
  "daredevil born again",
  "el imperio romano - asimov",
  "electron es zurdo - isaac asimov",
  "orlando furioso y oralndo inamorato",
  "mexico bizarro julio patan",
  "ciudad fantasma - bernardo esquinca",
  "demonia bernardo esquinca",
  "palinduro de mexico",
  "noticias del imperio",
  "la vista desde las últimas filas - neil gaiman",
  "coraline - neil gaiman",
  "La sombra del caudillo - martin luis guzman",
  "espejos una historia casi universal",
  "cualquier cuento de ryunosuke akutagawa",
  "sesenta relatos - dino buzzati",
  "los días enmascarados - carlos fuentes",
  "traslaciones poetas traductores (fondo de cultura economica",
  "el evangelio de lucas gavilan - vicente leñero",
  "cualquier cosa de ibargüengoitia",
  "Walter Mitty - James thuerber",
  "El cuento de carcasona - lord dunsany",
  "el japon fantasmal - lafcadio hearn",
  "los casos del detective kogoro akechi",
  "antalogía de poesía china (catedra)",
  "la gatomaquia - lope de vega",
  "the trials and tribulations of little red riding hood",
  "stranger in strange land - Robert a. heinlein",
  "el extraño misterioso - mark twain",
  "juana de arco - mark twain",
  "la semilla inmortal: los argumentos universales en el cine - jordi balló y xavier perez",
  "twinkle twinkle, luz brillante - kaori ekuni",
  "el mito del espejo negro: der mythus das schwarze speigel - hector chavarría",
  "seeds of anxiety",
  "El principio de Peter",
];
