const manga = [
  "iligals - boku no pico academia",
  "joseju no puni",
  "Melancolía dowman sayman",
  "dedededede",
  "piun piun",
  "ponkotsu ponko",
  "the unbeliavable gwenpool",
  "gotham central",
  "sandman",
  "hitomi chan is shy with strangers",
  "despera",
  "wizard of oz skottie young",
  "new frontier, DC",
  "demi-chan",
  "the music of marie",
  "yokohama kaidashi kikou",
  "gunnm alita",
  "Even a monkey can draw manga",
  "Spy x family",
  "kotonoba drive",
  "ketchup ninja",
  "Cucumber quest",
  "otonari complex",
  "yancha gai no anjou-san",
  "Ryushika ryushika",
  "Our lives after the apocalypse",
  "Superman whatever happened to the man of tomorrow",
  "marvels alex ross",
  "barmanwhatever happened to the caped crusader",
  "batman year one",
];
