const movies = [
  "the life of bryan",
  "knives out",
  "contact 1997",
  "Bo Burnham",
  "clue",
  "la camarista",
  "the florida project",
  "El nuevo nuevo testamento",
  "cleo de 5 a 7",
  "sunset boulevard",
  "american pop (1981)",
  "lost in translation",
  "little miss sunshine (2006)",
  "tenemos que hablar de kevin (2011)",
  "the rocky horror picture show (1975)",
  "onibaba el mito del sexo (1964)",
  "labyrinth (1986)",
  "memories of murder (2003)",
  "zodiac",
  "the purple rose of cairo",
  "vamos a jugar al infierno",
  "ikiru (1952)",
  "the straight story (1999)",
  "juan de los muertos",
  "magical girl (2014)",
  "bad genius (2017)",
  "canoa denuncia de un hecho vergonzoso (1976)",
  "godzila (1954)",
  "millennium actres",
  "tatami galaxi",
  "guardians of the galaxy",
  "draver",
  "baby driver",
  "The grand Budapest Hotel",
  "Aquatic Life",
  "simon del desierto (1954)",
  "Doctor Strange (2016)",
  "Frances Ha (2012)",
  "Marriage Story (2019)",
  "Enter the void (2009)",
];

